name: Generate Snake

on:
  # Jalankan otomatis setiap jam 12 malam
  schedule:
    - cron: "0 0 * * *" 
  
  # Bisa dijalankan manual juga
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Ganti 'sannydays' dengan username kamu jika berbeda
          github_user_name: sannydays
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            # PALET WARNA ROTI (Krem ke Cokelat Tua)
            dist/github-contribution-grid-snake-sepia.svg?color_snake=D2B48C&color_dots=#FFF8E1,#F5DEB3,#D2B48C,#A0522D,#5D4037
        env:
          # Token ini otomatis disediakan oleh GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
